# Generated by Django 3.2 on 2021-05-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='tokeny_type',
            new_name='token_type',
        ),
    ]
